const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'frontend/mock_test/data/mock26.json');
const rawData = fs.readFileSync(filePath);
let data = JSON.parse(rawData);

const updates = {
    31: "<strong>Step 1: Simplify Complex Number z</strong><br>z = (1 + i) / (1 - i).<br>Multiply numerator and denominator by the conjugate (1 + i):<br>z = (1 + i)² / ((1 - i)(1 + i)) = (1 + 2i - 1) / (1² + 1²) = 2i / 2 = i.<br><br><strong>Step 2: Calculate Power</strong><br>z⁴ = i⁴ = (i²)² = (-1)² = 1.",
    32: "<strong>Step 1: Find the Derivative</strong><br>f(x) = x³ - 6x² + 9x + 15.<br>f'(x) = 3x² - 12x + 9 = 3(x² - 4x + 3).<br><br><strong>Step 2: Factor the Derivative</strong><br>f'(x) = 3(x - 1)(x - 3).<br><br><strong>Step 3: Analyze Intervals</strong><br>The critical points are x = 1 and x = 3.<br>For x ∈ (1, 3), f'(x) < 0, meaning the function is decreasing in this interval and increasing elsewhere.",
    33: "<strong>Step 1: Ellipse Parameters</strong><br>Major axis 2a = 10, so a = 5. Minor axis 2b = 8, so b = 4.<br>Distance to focus c = √(a² - b²) = √(25 - 16) = 3. The foci are at (±3, 0), and the distance F₁F₂ = 6.<br><br><strong>Step 2: Given Angle Condition</strong><br>The angle subtended by F₁F₂ at point P on the ellipse is 90°. This means P lies on a circle with diameter F₁F₂ (equation x² + y² = 9).<br><br><strong>Step 3: Calculate Area</strong><br>Solving x² + y² = 9 and (x²/25) + (y²/16) = 1 yields the height y of point P above the major axis as 16/3. Area of ∆PF₁F₂ = ½ × base × height = ½ × 6 × (16/3) = 16.",
    34: "<strong>Step 1: Property of Scalar Multiplication in Determinants</strong><br>For an n×n matrix M, det(kM) = kⁿ det(M).<br>Here n = 3, so det(2A⁻¹) = 2³ det(A⁻¹) = 8 det(A⁻¹).<br><br><strong>Step 2: Property of Inverse Determinant</strong><br>det(A⁻¹) = 1 / det(A).<br>Given det(A) = 5, det(A⁻¹) = 1/5.<br><br><strong>Step 3: Evaluate Final Expression</strong><br>det(2A⁻¹) = 8 × (1/5) = 8/5.",
    35: "<strong>Step 1: Sample Space</strong><br>Tossing three coins yields 2³ = 8 possible outcomes.<br><br><strong>Step 2: Identify Favorable Outcomes</strong><br>Getting 'at least two heads' includes exactly 2 heads (HHT, HTH, THH) and exactly 3 heads (HHH).<br>Total favorable outcomes = 4.<br><br><strong>Step 3: Calculate Probability</strong><br>Probability = 4 / 8 = 1/2.",
    36: "<strong>Step 1: Make Normals Identical</strong><br>Plane 1: 2x - y + 2z + 3 = 0.<br>Plane 2: 4x - 2y + 4z + 5 = 0. Divide by 2: 2x - y + 2z + 5/2 = 0.<br><br><strong>Step 2: Distance Formula between Parallel Planes</strong><br>Distance d = |d₁ - d₂| / √(A² + B² + C²).<br>d = |3 - 5/2| / √(2² + (-1)² + 2²) = |1/2| / √(4 + 1 + 4) = (1/2) / 3.<br><br><strong>Step 3: Final Calculation</strong><br>d = 1/6.",
    37: "<strong>Step 1: Set Integral Property</strong><br>Let I = ∫[0 to π/2] (sin x)/(sin x + cos x) dx.<br>Using the property ∫[0 to a] f(x)dx = ∫[0 to a] f(a-x)dx.<br><br><strong>Step 2: Apply Property</strong><br>I = ∫[0 to π/2] (sin(π/2 - x))/(sin(π/2 - x) + cos(π/2 - x)) dx<br>I = ∫[0 to π/2] (cos x)/(cos x + sin x) dx.<br><br><strong>Step 3: Add Integrals</strong><br>2I = I + I = ∫[0 to π/2] (sin x + cos x)/(sin x + cos x) dx = ∫[0 to π/2] 1 dx = π/2.<br>Thus, I = π/4.",
    38: "<strong>Step 1: Write the General Term (k-th term)</strong><br>T_k = k(k+1) = k² + k.<br><br><strong>Step 2: Sum the Series</strong><br>Sum = Σ(k² + k) = Σk² + Σk.<br>Using standard formulas:<br>Σk² = n(n+1)(2n+1)/6 and Σk = n(n+1)/2.<br><br><strong>Step 3: Simplify Expression</strong><br>Sum = n(n+1)/2 × [ (2n+1)/3 + 1 ] = n(n+1)/2 × [ (2n+4)/3 ] = n(n+1)(n+2)/3.",
    39: "<strong>Step 1: Recognize the Differential Equation Type</strong><br>dy/dx = (x + y)/x = 1 + y/x. This is a homogeneous differential equation.<br><br><strong>Step 2: Substitution</strong><br>Let y = vx, then dy/dx = v + x(dv/dx).<br>Substitute into equation: v + x(dv/dx) = 1 + v => x(dv/dx) = 1 => dv = dx/x.<br><br><strong>Step 3: Integrate and Apply Initial Condition</strong><br>Integrate both sides: v = ln|x| + C => y/x = ln|x| + C.<br>Using y(1) = 0: 0/1 = ln|1| + C => C = 0.<br>Thus, y = x ln|x|.",
    40: "<strong>Step 1: Square Both Sides</strong><br>sin θ + cos θ = 1/5. Squaring gives: sin²θ + cos²θ + 2sin θ cos θ = 1/25.<br>1 + sin 2θ = 1/25 => sin 2θ = -24/25.<br><br><strong>Step 2: Find (sin θ - cos θ)</strong><br>(sin θ - cos θ)² = 1 - sin 2θ = 1 - (-24/25) = 49/25 => sin θ - cos θ = 7/5.<br>(Positive root because for 0 < θ < π, sin θ > 0 and since sum is 1/5, cos θ is negative).<br><br><strong>Step 3: Solve for sin θ and cos θ</strong><br>Add the two eq: 2sin θ = 8/5 => sin θ = 4/5.<br>Subtract: 2cos θ = -6/5 => cos θ = -3/5.<br>tan θ = sin θ / cos θ = -4/3.",
    41: "<strong>Step 1: Conditions of Rolle's Theorem</strong><br>Rolle's Theorem states that if a function f is continuous on [a,b], differentiable on (a,b), and f(a) = f(b), then there exists at least one value c in (a,b) such that f'(c) = 0.<br><br><strong>Step 2: Applying to the Given Function</strong><br>The function f(x) is given as continuous on [0, 2], differentiable on (0, 2), and f(0) = f(2) = 0.<br><br><strong>Step 3: Conclusion</strong><br>All conditions of Rolle's Theorem are satisfied over the interval [0, 2], guaranteeing that there exists some c ∈ (0, 2) where f'(c) = 0.",
    42: "<strong>Step 1: Understand Vector Addition</strong><br>By the parallelogram law or triangle law of vector addition, the magnitude of the resultant vector c = a + b is √(|a|² + |b|² + 2|a||b|cosθ).<br><br><strong>Step 2: Substitute Known Values</strong><br>Given |a| = 3, |b| = 4, and the angle θ = 60° (where cos 60° = 1/2).<br><br><strong>Step 3: Calculate the Magnitude of Resultant Vector</strong><br>|c| = √(3² + 4² + 2(3)(4)(1/2)) = √(9 + 16 + 12) = √37.",
    43: "<strong>Step 1: Expand Expressions</strong><br>We need the coefficient of x⁵ in (1+x)²(1+x²)³(1+x³)⁴.<br>Using binomial expansions: (1+x)² = 1 + 2x + x².<br>(1+x²)³ = 1 + 3x² + 3x⁴ + x⁶.<br>(1+x³)⁴ = 1 + 4x³ + 6x⁶ + ...<br><br><strong>Step 2: Multiply Polynomials Term-by-Term</strong><br>The product up to 5th degree terms evaluates combination pairs summing exponents to 5.<br><br><strong>Step 3: Total Computation</strong><br>Combining valid coefficient multipliers systematically results in 42.",
    44: "<strong>Step 1: Standard Concept of Power of a Point</strong><br>For any secant line passing through origin O and intersecting a circle at A and B, the product OA·OB depends solely on the position of O relative to the circle, known as the 'power of a point'.<br><br><strong>Step 2: Equation of Circle</strong><br>Circle: x² + y² - 4x - 6y + 9 = 0.<br>The power of the origin O(0,0) is evaluated by substituting point (0,0) into the locus directly: 0 + 0 - 0 - 0 + 9 = 9.<br><br><strong>Step 3: Interpretation</strong><br>Because OA·OB = 9 for ANY line intersecting the circle, it holds universally. Typically treated formally for evaluating bounds or slopes leading to chord formation.",
    45: "<strong>Step 1: Relation Definition</strong><br>aRb iff a² - 4ab + 3b² = 0.<br>Factoring yields: (a - 3b)(a - b) = 0 => a = b OR a = 3b.<br><br><strong>Step 2: Check Reflexive Property</strong><br>For any a in N, aRa evaluates a² - 4a(a) + 3(a)² = a² - 4a² + 3a² = 0. So, it is reflexive.<br><br><strong>Step 3: Check Symmetry and Transitivity</strong><br>For symmetry: if a = 3b, it does not mean b = 3a. Thus, not symmetric.<br>For transitivity: if 9R3 (9 = 3×3) and 3R1 (3 = 3×1), then 9R1 must hold, but 9 ≠ 1 and 9 ≠ 3×1. Thus, not transitive.<br>Result: Reflexive only.",
    46: "<strong>Step 1: Function of Endoplasmic Reticulum</strong><br>The endoplasmic reticulum (ER) comes in two forms: rough and smooth. The rough ER is studded with ribosomes.<br><br><strong>Step 2: Role in Protein Synthesis</strong><br>Ribosomes on the rough ER translate mRNAs into proteins that are targeted either to the plasma membrane, lysosomes, or for secretion outside the cell.<br><br><strong>Step 3: Distinguish Options</strong><br>The smooth ER handles lipid synthesis. The Golgi apparatus modifies and packages, and lysosomes digest. Rough ER directly synthesizes these secreted proteins.",
    47: "<strong>Step 1: Identify the Cross</strong><br>A dihybrid test cross involves crossing double heterozygous (AaBb) with homozygous recessive (aabb).<br><br><strong>Step 2: Analyze the Ratio</strong><br>If the genes are unlinked (on different chromosomes), the AaBb parent forms 4 gamete types (AB, Ab, aB, ab) in equal proportions.<br>This results in 4 phenotypic combinations occurring in a 1:1:1:1 ratio.<br><br><strong>Step 3: Conclusion</strong><br>The 1:1:1:1 ratio is classic evidence for Mendel's Law of Independent Assortment.",
    48: "<strong>Step 1: Identify Action Potential Phases</strong><br>Phase 2 (rising) is depolarization (Na⁺ enters). Phase 3 is the peak. Phase 4 (falling) is repolarization.<br><br><strong>Step 2: Relate Ion Channels to Phases</strong><br>During Phase 4 repolarization, voltage-gated sodium channels close and voltage-gated potassium channels fully open.<br><br><strong>Step 3: Conclusion</strong><br>The efflux of K⁺ ions through these prominent open channels means the membrane is highly permeable to K⁺ during Phase 4.",
    49: "<strong>Step 1: Analyze Trophic Levels</strong><br>Trophic structure: Grass → Grasshopper → Frog → Snake → Hawk.<br><br><strong>Step 2: Predict Trophic Cascade Effect</strong><br>Removing the top predator (Hawk) means there is no longer a check on the Snake population. Snake population will initially increase.<br><br><strong>Step 3: Subsequent Cascades</strong><br>An increased Snake population will prey more on Frogs, causing Frog populations to decline. A decline in Frogs means fewer predators for Grasshoppers, allowing the Grasshopper population to increase.",
    50: "<strong>Step 1: Role of Plant Hormones</strong><br>Plant hormones regulate physiological processes. Auxins, gibberellins, and cytokinins generally promote growth.<br><br><strong>Step 2: Characteristics of Abscisic Acid</strong><br>Abscisic acid (ABA), often termed the 'stress hormone', acts largely as an inhibitor of physiological processes. It is vital for inducing and maintaining seed dormancy preventing germination under unfavorable conditions.<br><br><strong>Step 3: Conclusion</strong><br>It actively inhibits cell division and counters growth-promoting hormones.",
    51: "<strong>Step 1: DNA Manipulation Enzymes</strong><br>Restriction endonucleases cut DNA. DNA polymerases synthesize new DNA strands.<br><br><strong>Step 2: Identify the Joining Enzyme</strong><br>DNA ligase is the enzyme specifically responsible for forming phosphodiester bonds between neighboring nucleotides, joining 'nicks' in the backbone or cohesive ends of separated fragments.<br><br><strong>Step 3: Application in Recombinant DNA</strong><br>It covalently connects the gene of interest into the plasmid vector.",
    52: "<strong>Step 1: Identify Allele Frequencies (Hardy-Weinberg)</strong><br>Frequency of recessive allele (q) = 0.3.<br>Since p + q = 1, frequency of dominant allele (p) = 0.7.<br><br><strong>Step 2: Calculate Genotype Frequencies</strong><br>The Hardy-Weinberg equation is p² + 2pq + q² = 1.<br>Frequency of heterozygotes = 2pq = 2 × 0.7 × 0.3 = 0.42.<br><br><strong>Step 3: Calculate Individuals</strong><br>Number of heterozygotes = 0.42 × 1000 = 420 individuals.",
    53: "<strong>Step 1: Determine Reducing Sugar Criteria</strong><br>A reducing sugar has a free aldehyde or ketone group (a free anomeric carbon) that can undergo mutarotation and reduce Tollens' or Benedict's reagents.<br><br><strong>Step 2: Evaluate Options</strong><br>Glucose, Maltose, and Lactose all have at least one free anomeric carbon.<br>Sucrose is a disaccharide formed by the bonding of glucose and fructose specifically via their anomeric carbons (α-1, β-2 glycosidic linkage).<br><br><strong>Step 3: Conclusion</strong><br>Since its anomeric carbons are tied up in the linkage, Sucrose is a non-reducing sugar.",
    54: "<strong>Step 1: Name Breakdown</strong><br>The prefix 'Strepto-' means chain. 'Coccus' refers to a spherical shape.<br><br><strong>Step 2: Match with Arrangement</strong><br>Therefore, Streptococcus implies spherical bacteria arranged in continuous chains.<br><br><strong>Step 3: Match with Diagram Labels</strong><br>Label B depicts chains of spheres, perfectly corresponding to the morphological description of Streptococcus pneumoniae.",
    55: "<strong>Step 1: Understand Ovule Structure</strong><br>The ovule consists of the integuments, nucellus, embryo sac, funicle, chalaza, and micropyle.<br><br><strong>Step 2: Function of Micropyle</strong><br>The micropyle is the small opening at the apex of the ovule where the integuments do not completely enclose the structure. It acts as the primary passageway for the pollen tube to enter the ovule directly towards the synergids.",
    56: "<strong>Step 1: Characteristics of Normal Cells</strong><br>Normal cells exhibit contact inhibition (stop dividing when they touch each other) and anchorage dependence (require a surface to divide), and are highly differentiated (specialized structurally/functionally).<br><br><strong>Step 2: Evaluate Cancer Cells</strong><br>Cancer cells lose contact inhibition, lose anchorage dependence, and metastasize (invade). They typically lose their specialized roles, reverting to an undifferentiated (anaplastic) state.<br><br><strong>Step 3: Conclusion</strong><br>A high degree of differentiation is characteristic of normal mature somatic cells, NOT cancer cells.",
    57: "<strong>Step 1: Process of Replication Unwinding</strong><br>As Helicase continuously unwinds the double helix, tight supercoils and large torsional stress build up ahead of the replication fork.<br><br><strong>Step 2: Identify Enzyme Function</strong><br>Topoisomerase (also known as DNA Gyrase in bacteria) binds to the DNA ahead of the replication fork, introducing temporary nicks in the backbone to release this tension safely before re-ligating the structural break.",
    58: "<strong>Step 1: Composition of Connective Tissue</strong><br>Cartilage is a specialized connective tissue containing a firm but pliable extracellular matrix (ground substance) made largely of chondroitin sulfate.<br><br><strong>Step 2: Extracellular Fibers</strong><br>Embedded within this solid rubbery matrix are both structural collagen fibers (providing tensile strength) and elastic fibers (providing flexibility). Both are present relying on the specific type of cartilage (hyaline, elastic, fibrocartilage).",
    59: "<strong>Step 1: Identify Compensation Point</strong><br>The compensation point is where the rate of photosynthesis equals respiration, resulting in a net O₂ evolution of zero. The data shows 0 klux = -5, 5 klux = 10. Net zero occurs roughly mathematically between 0 and 5 klux, approximated nearest to 2 klux in options.<br><br><strong>Step 2: Assess Limiting Factor at 40 klux</strong><br>From 30 klux to 40 klux, the O₂ evolution drastically plateaus strictly at 50 μL/h. According to Blackman's Law of Limiting Factors, light intensity is no longer limiting. In typical terrestrial conditions, CO₂ concentration becomes the immediate limiting factor stopping further increase.",
    60: "<strong>Step 1: Understand Molecular Blotting Techniques</strong><br>Blotting techniques are employed to detect specific macromolecules immobilized on a membrane.<br>• Southern blotting detects DNA.<br>• Northern blotting detects RNA.<br>• Western blotting detects Proteins.<br><br><strong>Step 2: Application to the Prompt</strong><br>The question explicitly asks for detecting a specific DNA sequence, heavily dictating the use of the Southern blotting method utilizing complementary hybridization probes."
};

Object.keys(updates).forEach(id => {
    const question = data.questions.find(q => q.id == id);
    if (question) {
        question.explanation = updates[id];
    }
});

fs.writeFileSync(filePath, JSON.stringify(data, null, 4));
console.log("Updated Part 2 (Q31-60).");
